# Generated by Django 5.1.7 on 2025-03-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
                ('date_naissance', models.DateField()),
                ('adresse', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bloque', models.BooleanField(default=False)),
                ('retard', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type_media', models.CharField(choices=[('Livre', 'Livre'), ('CD', 'CD'), ('DVD', 'DVD'), ('Jeu', 'Jeu de Plateau')], max_length=10)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('auteur', models.CharField(blank=True, max_length=250, null=True)),
                ('artiste', models.CharField(blank=True, max_length=250, null=True)),
                ('realisateur', models.CharField(blank=True, max_length=250, null=True)),
                ('emprunteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_mediatheque.emprunteur')),
            ],
        ),
    ]
