# Generated by Django 5.1.7 on 2025-03-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunteur',
            name='emprunts',
            field=models.ManyToManyField(blank=True, related_name='emprunteurs', to='gestion_mediatheque.media'),
        ),
    ]
